<p><img alt="DataOwl" width=150 src="http://gwsolutions.cl/Images/dataowl.png", align="left", hspace=0, vspace=5></p>

<h1 align="center">Numpy y Pandas</h1>

<h4 align="center">Arreglos y Dataframes</h4>
<pre><div align="center"> La idea de este notebook es que sirva para iniciarse en el preprocesamiento de datos.</div>


<div align="right"> En términos de código y estructura, este notebook esta basado en el BootCamp 
<a href="https://github.com/Shekhar-rv/Python-for-Data-Science-and-Machine-Learning-Bootcamp">Python for Data Science and Machine Learning</a>.
.</div></pre>

## ¿Qué es Numpy?

<p><img alt="Numpy" width=70 src="https://user-images.githubusercontent.com/50221806/81123350-b7c5bb00-8ee7-11ea-9bfc-88f676c80315.png", align="right", hspace=0, vspace=5></p>

NumPy es una extensión de Python, que le agrega mayor soporte para vectores y matrices, constituyendo una biblioteca de funciones matemáticas de alto nivel para operar con esos vectores o matrices.

Para instalar la librería puede hacerse a través del comando **pip** o el comando **conda** en la consola de comandos:





```cmd
conda install numpy

pip install numpy
```

In [3]:
# Importando la librería

import numpy as np

Numpy nos permite crear y trabajar con vectores (llamados arreglos) y matrices de forma simple, y se enfoca principalmente en añadir funciones matematicas, a diferencia de las listas que son estructuras de mayor complejidad. Existen varias maneras de construir un arreglo, entre ellas la más sencilla es realizarlo a partir de una lista, no obstante, podemos hacerlo a partir de una matriz o de comandos predefinidos.

In [4]:
# Creando arreglo a partir de una lista

my_list = [1,2,3,4,5]
my_array = np.array(my_list)

my_array

array([1, 2, 3, 4, 5])

In [5]:
# Creando arreglo a partir de una lista de listas


my_list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]
my_array_2 = np.array(my_list_of_lists)

my_array_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# Definiendo un array ordenado (Función arange)

arr = np.arange(0,11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
# Definiendo un array de ceros (Función zeros)

arr_0 = np.zeros(10)

arr_0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
# Definiendo un array de unos (Función ones)

arr_1 = np.ones(10)

arr_1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
# Definiendo un arreglo equiespaciado

arr = np.linspace(0,1,11)

arr

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [14]:
# Definiendo la matriz identidad


arr = np.eye(4)

Además de la creación de arreglos, existen además maneras de indexar y operaciones alrededor de los arreglos, no obstante no porfundizaremos en ellos ya que hoy en día esta librería no se utiliza en demasía, por lo que pasaremos a Pandas.

## ¿Qué es Pandas?
<p><img alt="Pandas" width=150 src="https://zhihuicao.files.wordpress.com/2016/05/pandas.png?w=399", align="right", hspace=0, vspace=5></p>

Pandas es una biblioteca de software escrita como extensión de NumPy para manipulación y análisis de datos para el lenguaje de programación Python. En particular, ofrece estructuras de datos y operaciones para manipular tablas numéricas y series temporales. 

Para instalar la librería puede hacerse a través del comando **pip** o el comando **conda** en la consola de comandos:



```cmd
conda install pandas

pip install pandas
```

In [15]:
#Importando la librería

import pandas as pd

<h3>Secciones</h3>

<div class="alert alert-danger" role="alert">
<ol>
    <li><a href="#section1"> Series</a></li>
    <li><a href="#section2"> DataFrames </a></li>
    <li><a href="#section3"> Datos faltantes (Missing Data) </a></li>
    <li><a href="#section4"> Agrupaciones (Groupby)</a></li>
    <li><a href="#section5"> Fusiones (Merge), Uniones (Join) y Concatenaciones</a></li>
</ol>
</div>
<hr>

<a id="section1"></a>
<h3>1. Series</h3>
<hr>

El primer tipo de datos principal que aprenderemos para los pandas es el tipo de datos **Serie**. Importemos Pandas y exploremos el objeto Serie.

<p><img alt="Dataframe" width=150 src="https://miro.medium.com/max/1284/1*iI8ltITQlsrX7Mc6E-OKKg.png", align="center", hspace=0, vspace=5></p>


Una serie es muy similar a un arreglo de NumPy (de hecho, está construida sobre el objeto de arreglo de NumPy). Lo que diferencia el arreglo de una Serie es que una Serie puede tener etiquetas de eje, lo que significa que puede ser indexada por una etiqueta, en lugar de solo una ubicación numérica. Tampoco necesita contener datos numéricos, puede contener cualquier objeto Python arbitrario.

Una serie puede ser creada a partir de un arreglo, de una lista o de un diccionario.

In [16]:
# Creando una serie

labels = ['a','b','c']
my_list = [10,20,30]

arr = np.array([10,20,30])

d = { 'a' : 10 , 'b' : 20 , 'c' : 30 }


Serie = pd.Series( data = my_list , index = labels )
Serie

a    10
b    20
c    30
dtype: int64

Los índices se utilizan de la misma manera que en las listas, diccionarios o arreglos:

In [17]:
# Llamando un elemento de la serie

Serie['b']

20

Cuando operamos dos series tenemos que tener cuidado, ya que estas se operan a partir de las etiquetas, no de la posición que utilizen en esta:

In [18]:
# Operación simple entre series


ser_1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])
ser_2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan'])

ser_1+ser_2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

<a id="section2"></a>
<h3>2. Dataframe</h3>
<hr>

Los DataFrames son el caballo de batalla de los pandas y están directamente inspirados en el lenguaje de programación R. Podemos pensar en un DataFrame como una matriz, donde cada columna es una serie. 

<p><img alt="Dataframe" width=450 src="https://vrzkj25a871bpq7t1ugcgmn9-wpengine.netdna-ssl.com/wp-content/uploads/2022/01/pandas-dataframe-integer-location.png", align="center", hspace=0, vspace=5></p>

Las columnas nos representan variables y las filas los datos, algunas veces indexados.

In [23]:
# Creando nuestro primer dataframe

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

df_1 = pd.DataFrame( data = arr )
df_2 = pd.DataFrame( data = arr , index = ["d_1","d_2","d_3"] , columns = ["V_1","V_2","V_3","V_4"])
df_2 

V_1  V_2  V_3  V_4
d_1    1    2    3    4
d_2    5    6    7    8
d_3    9   10   11   12

#### Leyendo y guardando ficheros
No solo podemos crear dataframes a partir de objetos creados en Python, además podemos leer datos de nuestra propia base datos o de un directorio externo.

In [24]:
# Leyendo un archivo .csv

df_covid19 = pd.read_csv("cases_country.csv")
df_covid19

Country_Region          Last_Update        Lat       Long_  \
0             Australia  2020-05-29 17:32:50 -25.000000  133.000000   
1               Austria  2020-05-29 17:32:50  47.516200   14.550100   
2                Canada  2020-05-29 17:32:50  60.001000  -95.001000   
3                 China  2020-05-29 17:32:50  30.592800  114.305500   
4               Denmark  2020-05-29 17:32:50  56.263900    9.501800   
..                  ...                  ...        ...         ...   
183  West Bank and Gaza  2020-05-29 17:32:50  31.952200   35.233200   
184      Western Sahara  2020-05-29 17:32:50  24.215500  -12.885800   
185               Yemen  2020-05-29 17:32:50  15.552727   48.516388   
186              Zambia  2020-05-29 17:32:50 -13.133897   27.849332   
187            Zimbabwe  2020-05-29 17:32:50 -19.015438   29.154857   

     Confirmed  Deaths  Recovered   Active  Incident_Rate  People_Tested  \
0       7173.0   103.0     6582.0    488.0      28.173938            NaN   
1      16655.0   668.0    15347.0    640.0     184.924054            NaN   
2      90658.0  7042.0    47454.0  36162.0     239.483077            NaN   
3      84119.0  4638.0    79380.0    101.0       5.988497            NaN   
4      11793.0   568.0    10438.0    787.0     203.601290            NaN   
..         ...     ...        ...      ...            ...            ...   
183      446.0     3.0      368.0     75.0       8.742671            NaN   
184        9.0     1.0        6.0      2.0       1.506705            NaN   
185      283.0    65.0       11.0    207.0       0.948838            NaN   
186     1057.0     7.0      779.0    271.0       5.749579            NaN   
187      149.0     4.0       28.0    117.0       1.002494            NaN   

     People_Hospitalized  Mortality_Rate  UID ISO3  
0                    NaN        1.435940   36  AUS  
1                    NaN        4.010808   40  AUT  
2                    NaN        7.767654  124  CAN  
3                    NaN        5.513618  156  CHN  
4                    NaN        4.816417  208  DNK  
..                   ...             ...  ...  ...  
183                  NaN        0.672646  275  PSE  
184                  NaN       11.111111  732  ESH  
185                  NaN       22.968198  887  YEM  
186                  NaN        0.662252  894  ZMB  
187                  NaN        2.684564  716  ZWE  

[188 rows x 14 columns]

In [27]:
# Leyendo archivo desde url

df_covid19_url = pd.read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")
df_covid19_url

Province/State         Country/Region        Lat       Long  1/22/20  \
0              NaN            Afghanistan  33.000000  65.000000        0   
1              NaN                Albania  41.153300  20.168300        0   
2              NaN                Algeria  28.033900   1.659600        0   
3              NaN                Andorra  42.506300   1.521800        0   
4              NaN                 Angola -11.202700  17.873900        0   
..             ...                    ...        ...        ...      ...   
261            NaN  Sao Tome and Principe   0.186360   6.613081        0   
262            NaN                  Yemen  15.552727  48.516388        0   
263            NaN                Comoros -11.645500  43.333300        0   
264            NaN             Tajikistan  38.861034  71.276093        0   
265            NaN                Lesotho -29.609988  28.233608        0   

     1/23/20  1/24/20  1/25/20  1/26/20  1/27/20  ...  5/19/20  5/20/20  \
0          0        0        0        0        0  ...     7653     8145   
1          0        0        0        0        0  ...      949      964   
2          0        0        0        0        0  ...     7377     7542   
3          0        0        0        0        0  ...      761      762   
4          0        0        0        0        0  ...       52       52   
..       ...      ...      ...      ...      ...  ...      ...      ...   
261        0        0        0        0        0  ...      251      251   
262        0        0        0        0        0  ...      167      184   
263        0        0        0        0        0  ...       11       34   
264        0        0        0        0        0  ...     1936     2140   
265        0        0        0        0        0  ...        1        1   

     5/21/20  5/22/20  5/23/20  5/24/20  5/25/20  5/26/20  5/27/20  5/28/20  
0       8676     9216     9998    10582    11173    11831    12456    13036  
1        969      981      989      998     1004     1029     1050     1076  
2       7728     7918     8113     8306     8503     8697     8857     8997  
3        762      762      762      762      763      763      763      763  
4         58       60       61       69       70       70       71       74  
..       ...      ...      ...      ...      ...      ...      ...      ...  
261      251      251      251      251      299      441      443      458  
262      197      209      212      222      233      249      256      278  
263       34       78       78       87       87       87       87       87  
264     2350     2551     2738     2929     3100     3266     3424     3563  
265        1        2        2        2        2        2        2        2  

[266 rows x 132 columns]

In [28]:
# Guardando un archivo localmente

df_covid19_url.to_csv("df_covid19.csv" , index="False")

#### Selección por columnas
Como ahora estamos trabajando con matrices, podemos querer seleccionar tanto por variables (Columnas) como por datos (Filas), por lo cual existen distintas formas de indexación, la primera a ver será la indexación por columnas.

Si indexamos 1 columna, entonces obtenemos una serie por resultado, pero si indexamos una lista de columnas obtenemos un dataframe

In [29]:
# Seleccionando 1 columna

df_covid19["Country_Region"]

0               Australia
1                 Austria
2                  Canada
3                   China
4                 Denmark
              ...        
183    West Bank and Gaza
184        Western Sahara
185                 Yemen
186                Zambia
187              Zimbabwe
Name: Country_Region, Length: 188, dtype: object

In [30]:
# Seleccionando 2 columnas

df = df_covid19[ ["Country_Region","Confirmed","Deaths","Recovered"] ]
df

Country_Region  Confirmed  Deaths  Recovered
0             Australia     7173.0   103.0     6582.0
1               Austria    16655.0   668.0    15347.0
2                Canada    90658.0  7042.0    47454.0
3                 China    84119.0  4638.0    79380.0
4               Denmark    11793.0   568.0    10438.0
..                  ...        ...     ...        ...
183  West Bank and Gaza      446.0     3.0      368.0
184      Western Sahara        9.0     1.0        6.0
185               Yemen      283.0    65.0       11.0
186              Zambia     1057.0     7.0      779.0
187            Zimbabwe      149.0     4.0       28.0

[188 rows x 4 columns]

#### Trabajando con variables

 * Para generar una nueva variable (columna) basta con crearla como si estuvieramos seleccionandola, y asignarle su valor.
 * Para eliminar una variable se utiliza la función **.drop( )**
 * Podemos indexar condiciones para establecer condiciones sobre las variables
 

In [31]:
# Creando una nueva variable

df["Active"] = df["Confirmed"]-df["Deaths"]-df["Recovered"]
df

C:\Users\alvar\anaconda\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


Country_Region  Confirmed  Deaths  Recovered   Active
0             Australia     7173.0   103.0     6582.0    488.0
1               Austria    16655.0   668.0    15347.0    640.0
2                Canada    90658.0  7042.0    47454.0  36162.0
3                 China    84119.0  4638.0    79380.0    101.0
4               Denmark    11793.0   568.0    10438.0    787.0
..                  ...        ...     ...        ...      ...
183  West Bank and Gaza      446.0     3.0      368.0     75.0
184      Western Sahara        9.0     1.0        6.0      2.0
185               Yemen      283.0    65.0       11.0    207.0
186              Zambia     1057.0     7.0      779.0    271.0
187            Zimbabwe      149.0     4.0       28.0    117.0

[188 rows x 5 columns]

In [41]:
# Eliminando la variable

df = df.drop("Active" , axis = 1)
df

KeyError: "['Active'] not found in axis"

In [33]:
# Condicionando variables

df_high_deaths = df[ df["Deaths"]>10000 ]
df_high_deaths

Country_Region  Confirmed    Deaths  Recovered
6           France   186364.0   28665.0    67309.0
10           Italy   232248.0   33229.0   152844.0
16  United Kingdom   272606.0   38243.0     1171.0
17              US  1731035.0  102201.0   399991.0
18           Spain   238564.0   27121.0   150376.0
21          Brazil   438238.0   26754.0   177604.0

#### Indexación por filas

Para comenzar, podemos establecer que una de nuestras columnas sea el indice para nuestro dataframe, para esto utilizamos la funcion **.set_index( )**

In [42]:
# Escogiendo un índice

df = df.set_index("Country_Region")
df

KeyError: "None of ['Country_Region'] are in the columns"

Para escoger 1 o 2 datos, utilizamos la función **.loc[ ]**.

In [37]:
# Escogiendo datos particulares

df.loc[ ["Argentina","Chile"] , ["Confirmed","Deaths"] ]

Confirmed  Deaths
Country_Region                   
Argentina         14702.0   510.0
Chile             90638.0   944.0

<a id="section3"></a>
<h3>3. Datos faltantes (Missing Data)</h3>
<hr>

Generalmente los datos vienen con valores faltantes en algunas de sus columnas, y esto puede traernos problema a la hora de trabajar y establecer criterios de decisión con la información que obtenemos de estos.

Debemos saber que hacer con la data que falta y cuándo hacerlo, para así no tener problemas a la hora de establecer un modelo, o obtener insights. 

Hay 3 formas usuales de trabajar con datos faltantes:
 
 1. La primera es simplemente eliminar las filas con datos faltantes, y evitarse el riesgo de asignar mal un valor. El problema que esto podría traer es que estamos omitiendo información relevante de nuestra muestra.
 2. La segunda es rellenar con algun valor determinado, ya sea la media, mediana u otro que nosotros consideremos. Aquí podríamos estar centralizando demasiado nuestros datos, y cuando las desviaciones son altas este método no es muy efectivo.
 3. Otro método consiste en utilizar modelos para tratar de predecir o remplanzar los datos faltantes, aunque esto podría tomarnos mucho tiempo y recursos.
 

<p><img alt="Multiple_Imputation" width=450 src="https://media.springernature.com/lw785/springer-static/image/chp%3A10.1007%2F978-3-319-43742-2_13/MediaObjects/339333_1_En_13_Fig3_HTML.gif", align="center", hspace=0, vspace=5></p>

En Python las funciones que nos ayudan a esto son **.dropna( )** para eliminar y la función **.fillna( )** para rellenar.

In [43]:
# Consideramos este dataframe

df = pd.DataFrame({'v_1':[1,2,np.nan],
                  'v_2':[5,np.nan,np.nan],
                  'v_3':[1,2,3]})
df

v_1  v_2  v_3
0  1.0  5.0    1
1  2.0  NaN    2
2  NaN  NaN    3

In [44]:
# Eliminando filas con NA

df.dropna()

v_1  v_2  v_3
0  1.0  5.0    1

In [45]:
# Eliminando columnas con NA

df.dropna(axis=1)

v_3
0    1
1    2
2    3

In [46]:
# Eliminando filas que tengan mas de n datos faltantes

n = 2
df.dropna( thresh=n )

# Esto se puede replicar para columnas con axis=1 en los argumentos

v_1  v_2  v_3
0  1.0  5.0    1
1  2.0  NaN    2

In [47]:
# Llenando con el promedio

df['v_1'] = df['v_1'].fillna( value = df['v_1'].mean() )
df

v_1  v_2  v_3
0  1.0  5.0    1
1  2.0  NaN    2
2  1.5  NaN    3

<a id="section4"></a>
<h3>4. Agrupaciones (Groupby)</h3>
<hr>

Para agrupar los datos en varios dataframes utilizando valores que se repitan en alguna de sus variables, utilizamos la funcion **.groupby( )**

In [49]:
# Agrupamos el conjunto por paises

df = df_covid19_url.dropna()
df

Province/State  Country/Region      Lat      Long  \
8        Australian Capital Territory       Australia -35.4735  149.0124   
9                     New South Wales       Australia -33.8688  151.2093   
10                 Northern Territory       Australia -12.4634  130.8456   
11                         Queensland       Australia -28.0167  153.4000   
12                    South Australia       Australia -34.9285  138.6007   
..                                ...             ...      ...       ...   
249            British Virgin Islands  United Kingdom  18.4207  -64.6400   
250          Turks and Caicos Islands  United Kingdom  21.6940  -71.7979   
255  Bonaire, Sint Eustatius and Saba     Netherlands  12.1784  -68.2385   
257       Falkland Islands (Malvinas)  United Kingdom -51.7963  -59.5236   
258         Saint Pierre and Miquelon          France  46.8852  -56.3159   

     1/22/20  1/23/20  1/24/20  1/25/20  1/26/20  1/27/20  ...  5/19/20  \
8          0        0        0        0        0        0  ...      107   
9          0        0        0        0        3        4  ...     3081   
10         0        0        0        0        0        0  ...       29   
11         0        0        0        0        0        0  ...     1058   
12         0        0        0        0        0        0  ...      439   
..       ...      ...      ...      ...      ...      ...  ...      ...   
249        0        0        0        0        0        0  ...        8   
250        0        0        0        0        0        0  ...       12   
255        0        0        0        0        0        0  ...        6   
257        0        0        0        0        0        0  ...       13   
258        0        0        0        0        0        0  ...        1   

     5/20/20  5/21/20  5/22/20  5/23/20  5/24/20  5/25/20  5/26/20  5/27/20  \
8        107      107      107      107      107      107      107      107   
9       3082     3084     3086     3087     3090     3092     3089     3090   
10        29       29       29       29       29       29       29       29   
11      1058     1058     1060     1061     1056     1057     1058     1058   
12       439      439      439      439      439      439      440      440   
..       ...      ...      ...      ...      ...      ...      ...      ...   
249        8        8        8        8        8        8        8        8   
250       12       12       12       12       12       12       12       12   
255        6        6        6        6        6        6        6        6   
257       13       13       13       13       13       13       13       13   
258        1        1        1        1        1        1        1        1   

     5/28/20  
8        107  
9       3092  
10        29  
11      1058  
12       440  
..       ...  
249        8  
250       12  
255        6  
257       13  
258        1  

[81 rows x 132 columns]

In [51]:
# Agrupamos el conjunto por paises

df = df_covid19_url.dropna()
countrys = df.groupby("Country_Region")
country

KeyError: 'Country_Region'

Cuando ya tenemos agrupados los datos por alguna variable podemos hacer diversas operaciones, entre ellas estan
 
 * Suma con la funcion **.sum( )**
 * Calcular el promedio con **.mean( )**
 * Calcular mínimo y máximo con **.max( )** y **.min( )** respectivamente.
 * Contar cuantos datos hay con **.count( )**
 * Realizar estadística descriptiva con **.describe( )**
 
Ademas con la función **.get_group( )** podemos obtener un dataframe específico.

In [52]:
# Hacemos una suma sobre los grupos

countrys.sum()

Lat       Long  1/22/20  1/23/20  1/24/20  1/25/20  \
Country/Region                                                             
Australia       -255.9695  1129.8623        0        0        0        0   
Canada           671.7607 -1237.6289        0        0        0        0   
China           1083.3367  3684.4197      548      643      920     1406   
Denmark          133.5995   -49.5161        0        0        0        0   
France            45.1348    57.5055        0        0        0        0   
Netherlands       54.9091  -270.3191        0        0        0        0   
United Kingdom   214.6518  -479.4887        0        0        0        0   

                1/26/20  1/27/20  1/28/20  1/29/20  ...  5/19/20  5/20/20  \
Country/Region                                      ...                     
Australia             4        5        5        6  ...     7072     7081   
Canada                1        1        2        2  ...    80493    81575   
China              2075     2877     5509     6087  ...    84063    84063   
Denmark               0        0        0        0  ...      198      198   
France                0        0        0        0  ...     2505     2631   
Netherlands           0        0        0        0  ...      200      200   
United Kingdom        0        0        0        0  ...     1320     1326   

                5/21/20  5/22/20  5/23/20  5/24/20  5/25/20  5/26/20  5/27/20  \
Country/Region                                                                  
Australia          7095     7099     7114     7114     7126     7139     7150   
Canada            82742    83947    85151    86106    87119    88090    88989   
China             84063    84081    84084    84095    84102    84103    84106   
Denmark             198      198      198      199      199      199      200   
France             2645     2709     2730     2850     2901     2960     2994   
Netherlands         200      200      201      201      202      202      202   
United Kingdom     1338     1349     1350     1357     1363     1372     1379   

                5/28/20  
Country/Region           
Australia          7165  
Canada            89976  
China             84106  
Denmark             200  
France             3055  
Netherlands         202  
United Kingdom     1381  

[7 rows x 130 columns]

In [53]:
# Podemos obtener el dataframe de un elemento en particular

countrys.get_group("Australia")

Province/State      Lat      Long  1/22/20  1/23/20  \
8   Australian Capital Territory -35.4735  149.0124        0        0   
9                New South Wales -33.8688  151.2093        0        0   
10            Northern Territory -12.4634  130.8456        0        0   
11                    Queensland -28.0167  153.4000        0        0   
12               South Australia -34.9285  138.6007        0        0   
13                      Tasmania -41.4545  145.9707        0        0   
14                      Victoria -37.8136  144.9631        0        0   
15             Western Australia -31.9505  115.8605        0        0   

    1/24/20  1/25/20  1/26/20  1/27/20  1/28/20  ...  5/19/20  5/20/20  \
8         0        0        0        0        0  ...      107      107   
9         0        0        3        4        4  ...     3081     3082   
10        0        0        0        0        0  ...       29       29   
11        0        0        0        0        0  ...     1058     1058   
12        0        0        0        0        0  ...      439      439   
13        0        0        0        0        0  ...      228      228   
14        0        0        1        1        1  ...     1573     1581   
15        0        0        0        0        0  ...      557      557   

    5/21/20  5/22/20  5/23/20  5/24/20  5/25/20  5/26/20  5/27/20  5/28/20  
8       107      107      107      107      107      107      107      107  
9      3084     3086     3087     3090     3092     3089     3090     3092  
10       29       29       29       29       29       29       29       29  
11     1058     1060     1061     1056     1057     1058     1058     1058  
12      439      439      439      439      439      440      440      440  
13      228      228      228      228      228      228      228      228  
14     1593     1593     1603     1605     1610     1618     1628     1634  
15      557      557      560      560      564      570      570      577  

[8 rows x 131 columns]

<a id="section5"></a>
<h3>5. Fusiones (Merges), Uniones (Joins) y Concatenaciones</h3>
<hr>
